# Site settings
title: 零博客 2021.Q3
description: >- # this means to ignore newlines until "baseurl:"
  Read blog on demand.
baseurl: "/21q3" # the subpath of your site, e.g. /blog
url: "https://agora0.github.io" # the hostname & protocol, e.g. http://example.com
github_username: agorahub

# Build settings
timezone: Asia/Singapore
theme: minima
exclude:
  - _posts/2021-07-23-STAND-時代革命-導演周冠威-電影就是創造力-樂觀是可以創造的.html
paginate: 50
plugins:
  - jekyll-feed
  - jekyll-paginate

